/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ammar.orderingsystem;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ammar
 * 
 * OrderingSystemView is the GUI of the Ordering System application.
 */
public class OrderingSystemView extends javax.swing.JFrame {

    /**
     * Creates new form OrderingSystemView
     */
    private final ArrayList<Item> itemsList;
    public DefaultListModel<String> nameListModel;
    public static DefaultListModel<String> cartListModel;
    public static DefaultTableModel checkoutTableModel;
    private ShoppingCart cart;
    private int itemQuantity;
    private int selectedItemIndex;
    private int selectedCartItemIndex;
    
    public OrderingSystemView(ArrayList list) {
        this.nameListModel = new DefaultListModel<>();
        OrderingSystemView.cartListModel = new DefaultListModel<>();
        OrderingSystemView.checkoutTableModel = new DefaultTableModel(new Object[] {
            "Item Name",
            "Quantity",
            "Price"
        }, 0);
        this.cart = new ShoppingCart();
        this.itemsList = list;
        this.itemQuantity = 0;
        
        this.itemsList.forEach((item)->{
            nameListModel.addElement(item.getName());
        });
        
        initComponents();
        // Inititalize all values to 0.0 on the checkout tab.
        cart.updateCheckoutDisplay();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        itemsPanel = new javax.swing.JPanel();
        itemNameLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemsListView = new javax.swing.JList<>();
        tabbedPane = new javax.swing.JTabbedPane();
        itemDescPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        itemDescNameLabel = new javax.swing.JLabel();
        itemDescPriceLabel = new javax.swing.JLabel();
        itemDescDescLabel = new javax.swing.JLabel();
        itemDescQuantityLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        addQuantityButton = new javax.swing.JButton();
        minusQuantityButton = new javax.swing.JButton();
        addToCartButton = new javax.swing.JButton();
        shoppingCartPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        shoppingCartItemsList = new javax.swing.JList<>();
        removeCartItemButton = new javax.swing.JButton();
        checkoutPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        itemsTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        discountLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();
        newTotalLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        toPayLabel = new javax.swing.JLabel();
        amountTextField = new javax.swing.JTextField();
        checkoutButton = new javax.swing.JButton();
        messageLabel = new javax.swing.JLabel();
        balanceLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ordering System");

        itemsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Items List", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("FreeMono", 1, 24))); // NOI18N

        itemNameLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        itemNameLabel.setText("Item Name");

        itemsListView.setModel(nameListModel);
        itemsListView.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                itemsListViewValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(itemsListView);

        javax.swing.GroupLayout itemsPanelLayout = new javax.swing.GroupLayout(itemsPanel);
        itemsPanel.setLayout(itemsPanelLayout);
        itemsPanelLayout.setHorizontalGroup(
            itemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(itemNameLabel)
                .addContainerGap(488, Short.MAX_VALUE))
            .addGroup(itemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(itemsPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(151, Short.MAX_VALUE)))
        );
        itemsPanelLayout.setVerticalGroup(
            itemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemsPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(itemNameLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(itemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itemsPanelLayout.createSequentialGroup()
                    .addContainerGap(65, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        tabbedPane.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tabbedPane.setPreferredSize(new java.awt.Dimension(598, 517));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setText("Item Name            :");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel2.setText("Item Price              :");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel3.setText("Item Description :");

        itemDescNameLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        itemDescNameLabel.setText("Name");

        itemDescPriceLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        itemDescPriceLabel.setText("Price");

        itemDescDescLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        itemDescDescLabel.setText("Desc");

        itemDescQuantityLabel.setText(Integer.toString(itemQuantity));

        jLabel5.setText("Quantity:");

        addQuantityButton.setText("+");
        addQuantityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addQuantityButtonActionPerformed(evt);
            }
        });

        minusQuantityButton.setText("-");
        minusQuantityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusQuantityButtonActionPerformed(evt);
            }
        });

        addToCartButton.setText("Add To Cart");
        addToCartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToCartButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout itemDescPanelLayout = new javax.swing.GroupLayout(itemDescPanel);
        itemDescPanel.setLayout(itemDescPanelLayout);
        itemDescPanelLayout.setHorizontalGroup(
            itemDescPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemDescPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(itemDescPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(itemDescPanelLayout.createSequentialGroup()
                        .addGroup(itemDescPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(itemDescPanelLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(itemDescNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, itemDescPanelLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(itemDescPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(itemDescPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(itemDescDescLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(itemDescPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(itemDescQuantityLabel)
                        .addGroup(itemDescPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(itemDescPanelLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(itemDescPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(minusQuantityButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addQuantityButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itemDescPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addToCartButton)
                                .addGap(70, 70, 70))))))
        );

        itemDescPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {itemDescDescLabel, itemDescNameLabel, itemDescPriceLabel});

        itemDescPanelLayout.setVerticalGroup(
            itemDescPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemDescPanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(itemDescPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(itemDescNameLabel))
                .addGap(18, 18, 18)
                .addGroup(itemDescPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(itemDescPriceLabel))
                .addGap(18, 18, 18)
                .addGroup(itemDescPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(itemDescDescLabel))
                .addGap(137, 137, 137)
                .addComponent(addQuantityButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(itemDescPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemDescQuantityLabel)
                    .addComponent(jLabel5)
                    .addComponent(addToCartButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(minusQuantityButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Item Description", itemDescPanel);

        shoppingCartItemsList.setModel(cartListModel);
        jScrollPane2.setViewportView(shoppingCartItemsList);

        removeCartItemButton.setText("Remove Selected Item");
        removeCartItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeCartItemButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout shoppingCartPanelLayout = new javax.swing.GroupLayout(shoppingCartPanel);
        shoppingCartPanel.setLayout(shoppingCartPanelLayout);
        shoppingCartPanelLayout.setHorizontalGroup(
            shoppingCartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shoppingCartPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(shoppingCartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
                    .addGroup(shoppingCartPanelLayout.createSequentialGroup()
                        .addComponent(removeCartItemButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        shoppingCartPanelLayout.setVerticalGroup(
            shoppingCartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shoppingCartPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(removeCartItemButton)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Shopping Cart", shoppingCartPanel);

        itemsTable.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        itemsTable.setModel(checkoutTableModel);
        itemsTable.setCellSelectionEnabled(true);
        itemsTable.setShowGrid(false);
        itemsTable.setShowHorizontalLines(true);
        jScrollPane3.setViewportView(itemsTable);

        jLabel4.setText("Total:");

        discountLabel.setText("jLabel6");

        jLabel6.setText("Discount:");

        jLabel7.setText("New Total:");

        totalLabel.setText("jLabel6");

        newTotalLabel.setText("jLabel6");

        jLabel8.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel8.setText("To Pay");

        toPayLabel.setText("jLabel6");

        amountTextField.setText("Enter amount");
        amountTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountTextFieldActionPerformed(evt);
            }
        });

        checkoutButton.setText("Checkout");
        checkoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutButtonActionPerformed(evt);
            }
        });

        messageLabel.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        messageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout checkoutPanelLayout = new javax.swing.GroupLayout(checkoutPanel);
        checkoutPanel.setLayout(checkoutPanelLayout);
        checkoutPanelLayout.setHorizontalGroup(
            checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkoutPanelLayout.createSequentialGroup()
                .addGroup(checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(checkoutPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(toPayLabel)
                            .addComponent(jLabel8))
                        .addGap(88, 88, 88)
                        .addComponent(amountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(checkoutPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newTotalLabel)
                    .addComponent(discountLabel)
                    .addComponent(totalLabel)
                    .addComponent(checkoutButton))
                .addGap(34, 34, 34))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkoutPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(balanceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(messageLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(checkoutPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        checkoutPanelLayout.setVerticalGroup(
            checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkoutPanelLayout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addGroup(checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(totalLabel))
                .addGap(18, 18, 18)
                .addGroup(checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(discountLabel))
                .addGap(18, 18, 18)
                .addGroup(checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(newTotalLabel))
                .addGroup(checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(checkoutPanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(toPayLabel))
                    .addGroup(checkoutPanelLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(amountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkoutButton))))
                .addGap(18, 18, 18)
                .addComponent(messageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(balanceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 15, Short.MAX_VALUE)
                .addGap(18, 18, 18))
            .addGroup(checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(checkoutPanelLayout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addGap(315, 315, 315)))
        );

        tabbedPane.addTab("Checkout", checkoutPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(itemsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(tabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(itemsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(153, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /*
    Change item description when user click an item in the item list.
    Every time a different item is clicked, the quantity label on item
    description pane will change to 0.
    */
    private void itemsListViewValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_itemsListViewValueChanged
        selectedItemIndex = this.itemsListView.getSelectedIndex();
        
        if(selectedItemIndex == -1)
            return;
            
        itemDescNameLabel.setText(itemsList.get(selectedItemIndex).getName());
        itemDescPriceLabel.setText(Double.toString(itemsList.get(selectedItemIndex).getPrice()));
        itemDescDescLabel.setText(itemsList.get(selectedItemIndex).getDescription());
        itemQuantity = 0;
        updateQuantityLabel();        
    }//GEN-LAST:event_itemsListViewValueChanged

    /*
    Add item quantity label on the item description pane.
    If no item is selected, cannot add quantity.
    */
    private void addQuantityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addQuantityButtonActionPerformed
        selectedItemIndex = this.itemsListView.getSelectedIndex();
        if(selectedItemIndex == -1)
            return;
        
        itemQuantity++;
        updateQuantityLabel();
    }//GEN-LAST:event_addQuantityButtonActionPerformed

    /*
    Substract item quantity label on the item description pane.
    If quantity is already 0, do nothing.
    */
    private void minusQuantityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusQuantityButtonActionPerformed
        if(itemQuantity == 0)
            return;
        
        itemQuantity--;
        updateQuantityLabel();
    }//GEN-LAST:event_minusQuantityButtonActionPerformed

    /*
    Add object ShoppingCartItem to cart.
    ShoppingCartItem is an object that inherits from class Item,
    with addition of attributes, which is quantity.
    */    
    private void addToCartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToCartButtonActionPerformed
        selectedItemIndex = this.itemsListView.getSelectedIndex();
        
        if(selectedItemIndex == -1 || itemQuantity == 0)
            return;
        
        Item selectedItem = itemsList.get(selectedItemIndex);
        
        ShoppingCartItem cartItem;
        cartItem = new ShoppingCartItem(
                selectedItem.getName(),
                selectedItem.getDescription(),
                selectedItem.getPrice(),
                itemQuantity
        );

        cart.addItem(cartItem);
    }//GEN-LAST:event_addToCartButtonActionPerformed

    /*
    Remove item from shopping cart.
    If no item is selected, do nothing.
    */
    private void removeCartItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeCartItemButtonActionPerformed
        selectedCartItemIndex = shoppingCartItemsList.getSelectedIndex();
        
        if(selectedCartItemIndex == -1)
            return;
        
        cart.removeItem(selectedCartItemIndex);
    }//GEN-LAST:event_removeCartItemButtonActionPerformed

    private void amountTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountTextFieldActionPerformed

    /*
    Empty cart if amount that customer give is not less than the total price after dicsount.
    If cart is empty, do nothing.
    */
    private void checkoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutButtonActionPerformed
        if(cart.getItems().isEmpty())
            return;
        
        double paying = Double.parseDouble(amountTextField.getText());
        if(paying < cart.totalPriceAfterDiscount()) {
            messageLabel.setText("Insufficient Amount!");
            return;
        }
        
        cart.checkout(paying);
    }//GEN-LAST:event_checkoutButtonActionPerformed

    /*
    Update quantity display in item description tab to match with variable itemQuantity.
    */
    private void updateQuantityLabel(){
        itemDescQuantityLabel.setText(Integer.toString(itemQuantity));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addQuantityButton;
    private javax.swing.JButton addToCartButton;
    private javax.swing.JTextField amountTextField;
    public static javax.swing.JLabel balanceLabel;
    private javax.swing.JButton checkoutButton;
    private javax.swing.JPanel checkoutPanel;
    public static javax.swing.JLabel discountLabel;
    private javax.swing.JLabel itemDescDescLabel;
    private javax.swing.JLabel itemDescNameLabel;
    private javax.swing.JPanel itemDescPanel;
    private javax.swing.JLabel itemDescPriceLabel;
    private javax.swing.JLabel itemDescQuantityLabel;
    private javax.swing.JLabel itemNameLabel;
    private javax.swing.JList<String> itemsListView;
    private javax.swing.JPanel itemsPanel;
    private javax.swing.JTable itemsTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JLabel messageLabel;
    private javax.swing.JButton minusQuantityButton;
    public static javax.swing.JLabel newTotalLabel;
    private javax.swing.JButton removeCartItemButton;
    private javax.swing.JList<String> shoppingCartItemsList;
    private javax.swing.JPanel shoppingCartPanel;
    private javax.swing.JTabbedPane tabbedPane;
    public static javax.swing.JLabel toPayLabel;
    public static javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables
}
